trigger:
  tags:
    include:
      - 'v*'
  branches:
    include:
      - 'master'

pool: vmssagentpool      

pr:
  branches:
    include:
      - "master"

resources:
  repositories:
    - repository: templates
      type: github
      name: chaseappio/devops-ci-templates
      ref: refs/heads/master
      endpoint: chaseappio

variables:  
- template: vars.yml@templates
- name: sdk_version
  value: 7.x
- name: sln_path
  value: Microsoft.SCIM.sln

stages:
  - stage: prepare
    jobs: 
     - job: version
       steps:
         - template: version.yml@templates

  - stage: build
    condition: "succeeded()"
    jobs:
      - job: build
        steps:
         - template: build.yml@templates
           parameters:
            sdk_version: $(sdk_version)
            sln_path: $(sln_path)
         - template: pack.steps.yml@templates
           parameters:
             sln_path: $(sln_path)            
             condition: "and(succeeded(),eq(variables['publish_build'],'true'))"
